CONTACT_TOLERANCE = 0.5
CONFIRM_TOLERANCE = 1.0

DEFAULT_SCREW_DIAMETER = 3.0
DEFAULT_SCREW_DEPTH = 12.0
DEFAULT_SCREW_SPACING = 250.0
DEFAULT_SCREW_MARGIN = 50.0

ATTRIBUTE_GROUP = "FusionCabinetAutomation"
